main: me.armar.plugins.autorank.Autorank
name: Autorank
url: http://dev.bukkit.org/bukkit-plugins/ontime/
version: ${project.version}
authors: [Staartvin, Armarr]
softdepend: [ Vault, GroupManager, Privileges, bPermissions, PermissionsEx, PermissionsBukkit, DroxPerms,
              PowerfulPerms, mcMMO, Factions, afkTerminator, OnTime, RoyalCommands, UltimateCore, Statz,
              AdvancedAchievements, BattleLevels, Jobs, RPGme, uSkyBlock, WorldEdit, WorldGuard, AcidIsland,
              ASkyBlock, GriefPrevention, Essentials, Quests, PlayerPoints, Votifier, CMI, UhcStats, Towny, McRPG,
              PlaceholderAPI, AureliumSkills ]
description: Reward players based on their stats.
api-version: 1.13
commands:
  ontime:
    description: Master command of AutoRank
    usage: Autorank is disabled. Check your server.log!
    aliases: [ot]
permissions:
  ontime.check:
    description: Allows checking the recommended rank.
    default: true
  ontime.checkothers:
    description: Allows checking the recommended rank of other players.
    default: op
  ontime.leaderboard:
    description: Allows looking at the leaderboards.
    default: true
  ontime.exclude:
    description: Excludes groups or users from the ontime checks.
    default: false
  ontime.timeexclude:
    description: Excludes groups or users from the playtime updates.
    default: false
  ontime.set:
    description: Allows changing playtime of any player
    default: op
  ontime.add:
    description: Allows adding to playtimes.
    default: op
  ontime.remove:
    description: Allows substracting from playtimes.
    default: op
  ontime.debug:
    description: Displays debugging information.
    default: op
  ontime.reload:
    description: Allows reloading the config.
    default: op
  ontime.import:
    description: Allows importing old storage.
    default: op
  ontime.archive:
    description: Allows a player to archive old storage.
    default: op
  ontime.noticeonupdate:
    description: When a new update is available, Autorank will tell all players with this permission that a new version is available.
    default: op
  ontime.sync:
    description: Allows a player to do /ot sync
    default: op
  ontime.syncstats:
    description: Allows a player to do /ot syncstats
    default: op
  ontime.complete:
    description: Allows a player to do /ot complete
    default: op
  ontime.forcecheck:
    description: Allows a player to forcecheck another player
    default: op
  ontime.noticeonwarning:
    description: Allows a player to see warnings when problems occur with Autorank.
    default: op
  ontime.convert.playerdata:
    description: Allows a player to convert the playerdata to UUID format.
    default: op
  ontime.convert.data:
    description: Allows a player to convert the storage.yml to UUID format.
    default: op
  ontime.help:
    description: Allows a player to view a list of commands
    default: true
  ontime.leaderboard.exclude:
    description: Exempts a player from the leaderboard.
    default: false
  ontime.leaderboard.broadcast:
    description: Allows a player to broadcast the leaderboard.
    default: op
  ontime.leaderboard.force:
    description: Allows a player to force-update the leaderboard.
    default: op
  ontime.track:
    description: Allows a player to view their requirement progress.
    default: true
  ontime.gset:
    description: Allows changing global playtime of players.
    default: op
  ontime.hooks:
    description: Allows viewing the available hooks for Autorank
    default: op
  ontime.gcheck:
    description: Allows checking global time.
    default: op
  ontime.gadd:
    description: Allows adding global time.
    default: op
  ontime.view:
    description: Allows previewing ranking paths before choosing
    default: true
  ontime.choose:
    description: Allows choosing ranking paths
    default: true
  ontime.times.self:
    description: Allows checking your own time statistics.
    default: true
  ontime.times.others:
    description: Allows checking time statistics of other players.
    default: op
  ontime.convert.simpleconfig:
    description: Allows a player to convert storage from SimpleConfig to Paths
    default: op
  ontime.convert.advancedconfig:
    description: Allows a player to convert storage from AdvancedConfig to Paths
    default: op
  ontime.backup.data:
    description: Allows a player to backup storage files
    default: op
  ontime.deactivate:
    description: Allows a player to deactivate a path
    default: true
  ontime.info.self:
    description: Allows a player to view their own info.
    default: true
  ontime.info.others:
    description: Allows a player to view info of other players.
    default: op
  ontime.editor.path.assign:
    description: Allows a player to assign a path to another player
    default: op
  ontime.editor.path.assign.force:
    description: Allows a player to assign a path to another player by force
    default: op
  ontime.editor.path.unassign:
    description: Allows a player to unassign a path from another player
    default: op
  ontime.editor.complete.requirement:
    description: Allows a player to complete a requirement for a path from another player.
    default: op
  ontime.editor.complete.path:
    description: Allows a player to complete a path for another player.
    default: op
  ontime.migrate:
    description: Allows a player to migrate data from another plugin to Autorank
    default: op